### ISSUE TITLE
Running cmd in container on remote docker host hangs

### ISSUE THREAD

**Issue by xmik** [swipely/docker-api#331]
I have a problem with running a command in docker container on **remote docker host**. When I do that locally, all is fine. On remote docker host, the command is invoked, I see stdout, but it hangs then. Am I doing something wrong?

How to reproduce:
```ruby
base_image = Docker::Image.create('fromImage' => 'alpine:3.2')
container = base_image.run(['/bin/echo', '123'])
container.attach(stream: true, stdout: true,
                 stderr: true, logs: true, tty: false) do |stream, chunk|
  puts("#{stream}: #{chunk}".strip())
end
container.delete()
```

This is similar to #251.

------
Update
This works fine (locally and remotely) when using docker client command line:
```
$ DOCKER_HOST=tcp://<remote_ip>:2375 docker run -ti alpine:3.2 /bin/echo 123
123
$
```

**Comment by tlunter** [comment]
@xmik can you run the same code with the environment variable `EXCON_DEBUG=true` on? I'm curious if you're actually receiving anything from the daemon.  Since you're definitely connecting to the remote host, and running some commands we can assume this isn't an SSL problem.

Which versions of docker are you running?  I'm wondering if there was an API update that we're not using correctly now.  It does seem odd that an HTTP endpoint would behave differently remotely versus locally.

Lastly: If you run `docker start CONTAINER_ID` on that container on the remote host after the hang, does it complete successfully?

**Comment by xmik** [comment]
Thanks for fast response. Today I am on different workstation (different computer, different place) and the ruby snippet above works fine (!). Tommorrow I'll be on the first workstation and will give more feedback tommorrow.

**Comment by tlunter** [comment]
@xmik oh boy! Ok, we can close this for now.  Feel free to open it back up if you've figured something out!

**Comment by xmik** [comment]
I gave it another try. This is clearly not a `docker-api` issue. Some kind of solution for me is to stream logs after the command is run, instead of seeing them live (like in [dockly](https://github.com/swipely/dockly/blob/master/lib/dockly/build_cache/docker.rb#L104)). 

Sorry for bothering you @tlunter with the false issue.

**Comment by tlunter** [comment]
@xmik one thing that I've seen the docker client do is:

1. Create the container (but not start)
2. Attach to the container (in a different thread)
3. Start the container

This works really well in Go with goroutines, but with a bit of thread management can work.  Maybe give that a try?
