### ISSUE TITLE
logs behavior seems odd

### ISSUE THREAD

**Issue by c6decacb79e8ca046dcb61002aac5280** [swipely/docker-api#410]
Hello guys
I am trying to get the logs from the containers and put them in a queue, but the logs() and streaming_logs() act strange

so right now we have shell scripts that basically do this

`curl -s --no-buffer -XGET --unix-socket /var/run/docker.sock "http:/containers/CONTINER_ID/logs?stdout=1&tail=1&follow=1"
`
so we get one line at a time, that line goes into the queue

with the ruby api we are unable to replicate this behavior

we tried:
`
container.streaming_logs(stdout: true, tail: 1, follow: true) { |stream, chunk| enqueue_log("#{container_name}:  #{chunk}")  }
`
but if nothing changes it keeps getting the same message (the last one) over and over.

and also later on we get the _Docker::Error::TimeoutError,_ we cannot increase the timeout as this runs continuously  

any ideas about how to achieve that?

**Comment by Soulou** [comment]
Probably related to https://github.com/swipely/docker-api/pull/522

**Comment by mpalmer** [comment]
Pretty sure this down to the difference in the format of the streamed logs depending on whether the container is configured as having a TTY or not.  The value of the `tty: true/false` option passed to `#logs`/`#streaming_logs` must match the value of the `c.info["Config"]["Tty"]` container variable, otherwise all heck breaks loose -- the wrong parser is invoked, and either no logs come through, or all logs come through in one giant string.

It is impossible to overstate the amount of swearing I have done in the last hour or so as I figured that out.
