### ISSUE TITLE
fix travis build

### ISSUE THREAD

**Issue by grosser** [swipely/docker-api#437]
all my PRs are red even when they change nothing ...

@tlunter

**Comment by grosser** [comment]
@tlunter do you know what is going on or want me to try to fix travis ?

**Comment by tlunter** [comment]
@grosser Sorry, currently very busy with internal projects. The failures you're seeing are due to hidden secrets. If there are more than just the three failures, then we can try and solve them.  I think the ruby 1.9.3 tests are failing due to a bad gem cache on Travis, which I'm not sure the best way to solve other than deleting the cache.

**Comment by grosser** [comment]
just clear the cache then ? ... I can't do that :D

**Comment by tlunter** [comment]
Done, now it looks like the error is due to the most recent json gem not being compatible with ruby < 2.0.0.

**Comment by grosser** [comment]
Can we drop 1.9 ... It's dead anyway ?

**Comment by grosser** [comment]
https://github.com/swipely/docker-api/pull/440
