### ISSUE TITLE
Newest docker remote API now 1.24, whats the schedule of docker-api

### ISSUE THREAD

**Issue by cmingxu** [swipely/docker-api#441]
Are we going to support new version of docker remote api

**Comment by mattheworiordan** [comment]
In fact this is now a blocker for me so I am having to "hack" this gem unfortunately.

In order to use Docker for Mac with `IPAMConfig`, you need version 1.24+ so that the gateway & ip address are setup correctly.  I would just bump the version number, but I have no idea what consequences could be so for now I'm hacking that single request to use the latest version of the API

**Comment by hekaldama** [comment]
relates to #423

**Comment by lbdremy** [comment]
Nothing new related to this issue ?

**Comment by RunsFor** [comment]
Here is pull request related to this issue #462

**Comment by RunsFor** [comment]
Seems the project was not actively maintained last time.
@tlunter Hey. Do you have time to review this and some related issues?

It would be great to add the ability (#462) to explicitly set docker remote api version you want to use.

If any help needed, let me know.

Thanks!

**Comment by spiderpug** [comment]
Encountering this as well. Using a really bad patch for now:

```ruby
Docker.send(:remove_const, 'API_VERSION')
Docker.const_set('API_VERSION', '1.24')
```
