### ISSUE TITLE
How to Container#run detached and return immediately?

### ISSUE THREAD

**Issue by preston** [swipely/docker-api#471]
Currently, the documentation provides a single example of `::Docker::Container#run` with a required argument. I've figured out that you can pass `nil` to use the default RUN command, but #run(..) is always a blocking call. How do you use ::Docker::Container#run while also specifying that it should start the container as completely detached and return immediately to the caller?

**Comment by preston** [comment]
Also note that using #exec with an empty or nil command argument array doesn't provide a workaround:

    (byebug) container.exec(nil, detach: true)
    *** Docker::Error::ServerError Exception: No exec command specified
    
    (byebug) container.exec([], detach: true)
    *** Docker::Error::ServerError Exception: No exec command specified

**Comment by preston** [comment]
Any hints here? It's pretty frustrating that this call always blocks. :(

**Comment by staticfox** [comment]
+1

**Comment by tlunter** [comment]
@preston 

`Container#run` starts the current container, commits it, then runs the command in the resulting image that was committed.

Is this what you're trying to do?

If not, try taking a look at `Docker::Container.create` which given an image, you can pass an empty command (if a default exists), and with the resulting container call `start` which does not block.

It seems like your current setup is blocking because `Container#run` is calling `start` on the current container and waiting for it: https://github.com/swipely/docker-api/blob/master/lib/docker/container.rb#L41-L43
